services:
  mysql:
    image: mysql:8.0
    container_name: animegen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: animegen
    ports:
      - "3307:3306"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    container_name: animegen-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: animegen-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
